// // Generated by CoffeeScript 1.6.3
// (function() {
//   var Postcards, fs,
//     __hasProp = {}.hasOwnProperty,
//     __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };
//
//   fs = require("fs");
//
//   module.exports = Postcards = (function(_super) {
//     __extends(Postcards, _super);
//
//     function Postcards(api) {
//       this.api = api;
//       this.path = "postcards";
//       this;
//     }
//
//     Postcards.prototype.create = function(_object, callback) {
//       var method = 'POST';
//       if(!(_object.front instanceof Buffer)) {
//         if(_object.front.substr(0,1) === '@') {
//           method = 'POST_FORM';
//           _object.front = fs.createReadStream(_object.front.substr(1));
//         }
//       } else {
//         method = 'POST_FORM';
//       }
//
//       if(_object.back) {
//         if (!(_object.back instanceof Buffer)) {
//           if (_object.back.substr(0, 1) === '@') {
//             method = 'POST_FORM';
//             _object.back = fs.createReadStream(_object.back.substr(1));
//           }
//         } else {
//           method = 'POST_FORM';
//         }
//       }
//
//       this.api.request(method, this.path, _object, callback);
//       return this;
//     };
//
//     return Postcards;
//
//   })(require("./common"));
//
// }).call(this);
