// Generated by CoffeeScript 1.6.3
(function() {
  var Commons;

  module.exports = Commons = (function() {
    function Commons(api) {
      this.api = api;
      this;
    }

    Commons.prototype.list = function(offset, count, callback) {
      var data;
      if (offset == null) {
        offset = 0;
      }
      if (count == null) {
        count = 10;
      }
      data = {
        offset: offset,
        count: count
      };
      if (typeof offset === "function") {
        callback = offset;
        data.offset = 0;
      }
      this.api.request("GET", this.path, data, callback);
      return this;
    };

    Commons.prototype.get = function(_id, callback) {
      if (typeof _id !== "string") {
        if (typeof _id === "function") {
          callback = _id;
        }
        if (typeof callback === "function") {
          callback("ID can not be empty for this operation", null);
        } else {
          throw new Error("ID can not be empty for this operation, Callback is empty");
        }
        return this;
      } else {
        this.api.request("GET", "" + this.path + "/" + _id, {}, callback);
        return this;
      }
    };

    return Commons;

  })();

}).call(this);
