// Generated by CoffeeScript 1.6.3
(function() {
  var Jobs,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Jobs = (function(_super) {
    __extends(Jobs, _super);

    function Jobs(api) {
      this.api = api;
      this.path = "jobs";
      this;
    }

    Jobs.prototype.create = function(_object, callback) {
      var _i, _o, _ref;
      _ref = _object.objects != null;
      for (_i in _ref) {
        _o = _ref[_i];
        _object["object" + (++_i)] = _o;
      }
      delete _object.objects;
      this.api.request("POST", this.path, _object, callback);
      return this;
    };

    return Jobs;

  })(require("./common"));

}).call(this);
