// Generated by CoffeeScript 1.6.3
(function() {
  var Postcards, fs,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fs = require("fs");

  module.exports = Postcards = (function(_super) {
    __extends(Postcards, _super);

    function Postcards(api) {
      this.api = api;
      this.path = "postcards";
      this;
    }

    Postcards.prototype.create = function(_object, callback) {
      if ("@" === _object.front.substr(0, 1 || "@" === _object.back.substr(0, 1))) {
        if ("@" === _object.front.substr(0, 1)) {
          _object.front = fs.createReadStream(_object.front.substr(1));
        }
        if ("@" === _object.back.substr(0, 1)) {
          _object.back = fs.createReadStream(_object.back.substr(1));
        }
        this.api.request("POST_FORM", this.path, _object, callback);
      } else {
        this.api.request("POST", this.path, _object, callback);
      }
      return this;
    };

    return Postcards;

  })(require("./common"));

}).call(this);
