// Generated by CoffeeScript 1.6.3
(function() {
  var Settings,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Settings = (function(_super) {
    __extends(Settings, _super);

    function Settings(api) {
      this.api = api;
      this.path = "settings";
      this;
    }

    return Settings;

  })(require("./common"));

}).call(this);
