name: Run Tests

on: [push, pull_request]

jobs:
  node_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Create NYC folder
        run: mkdir .nyc_output
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Run tests
        run: npm run test
      - name: Run integration tests
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          LIVE_API_KEY: ${{ secrets.LIVE_API_KEY }}
        run: npm run test:integration
      - name: Coverage
        if: matrix.node == 20
        run: npm run test-lcov
      - name: Coveralls
        if: matrix.node == 20
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
